spring:
  datasource:
    url: jdbc:mysql://localhost:3306/movie_recommend?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
    mode: HTML
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zhang.entity
server:
  port: 8080